name: Build Succeds on Pr

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencis
        uses: npm install
      - name: Generate the client
        uses: npm run db:generate
      - name: Run Build
        uses: npm run build